[book]
authors = ["Tuyen Pham"]
language = "en"
multilingual = false
src = "src"
title = "Tuyen mdBook"

[rust]
edition = "2018"

[build]
build-dir = "book/"
create-missing = true

[preprocessor.index]

[preprocessor.links]

[output.html]
no-section-label = true
default-theme = "ayu"
preferred-dark-theme = "ayu"
copy-fonts = true
git-repository-url = "https://github.com/tuyen-mdbook/tuyen-mdbook.github.io"
git-repository-icon = "fa-github"

[output.html.print]
enable = true

[output.html.fold]
enable = true
level = 2

[output.html.playground]
editable = true
copy-js = true
line-numbers = true

[output.html.search]
limit-results = 15